
/*
❯ openssl dgst -sha1 test.txt
SHA1(test.txt)= 937e7bb5864000846471f854bf873c547572f047
*/

#include <stdio.h>
#include <string.h>
#include <openssl/evp.h>

int main(){

    //We allocate the message to hash in the memory
    char message[] = "This is the message to hash!!!";

    //We define the pointer to the message digest context
    EVP_MD_CTX *md;

    //We initialize the message digest context
    md = EVP_MD_CTX_new();

    //The first parameter is the context
    //The second parameter is the name of the algorithm
    EVP_DigestInit(md, EVP_sha1());

    //The first parameter is the context
    //The second parameter is the message
    //The third parameter is the length of the message
    EVP_DigestUpdate(md, message, strlen(message));

    //Now the algo has got all the informations
    //We need now to actually compute it with the finalization
    
    //We define the buffer in memo where we store the digest
    //In this case sha1 is returning a digest 160bits long, so 20 bytes
    unsigned char md_value[20];

    //How many data have been generated by the OpenSSL lib.
    int md_len;

    /*
        We are ready to finalize
        The first parameter is the context
        The second parameter is the buffer where we store the digest
        The third parameter is the length of the digest, passed by reference because it will be modified
        If you are insure about the size of the buffer to allocate in memory for the result
        You will still obtain in teh md_len variable the size of the message that have been actually written.
    */
    EVP_DigestFinal(md, md_value, &md_len);

    //We now free the memory allocated for the context
    EVP_MD_CTX_free(md);

    //We print the digest
    printf("The digest's value is:  ");

    //Here we create the cycle to print the digest
    //THe %02x is a format string that prints the value in hexadecimal
    for(int i=0; i<md_len;i++)
        printf("%02x", md_value[i]);

    return 0;
}